sections:
- identifier: Sekce1
  mandatory: true
  description: the purpose of Sekce1
  options:
  - !String
    identifier: Option 1
    mandatory: true
    description: the purpose of Option 1
    single_value: true
  - !Signed
    identifier: Option 2
    mandatory: true
    description: the purpose of Option 2
    single_value: false
    min_value: -5
    max_value: 5
  - !Enum
    identifier: Option 3
    mandatory: false
    description: the purpose of Option 3
    single_value: false
    default_values:
    - Value1
    allowed_values:
    - Value1
    - Value2
    - Value3
- identifier: Cisla
  mandatory: false
  description: the purpose of Cisla
  options:
  - !Signed
    identifier: cele
    mandatory: true
    description: the purpose of cele
    single_value: true
  - !Signed
    identifier: cele_bin
    mandatory: false
    description: the purpose of cele_bin
    single_value: true
    default_values:
    - 0b00000001
  - !Unsigned
    identifier: cele_hex
    mandatory: false
    description: the purpose of cele_hex
    single_value: false
    default_values:
    - 0xABCD
  - !Float
    identifier: float1
    mandatory: true
    description: the purpose of float1
    single_value: true
  - !Float
    identifier: float2
    mandatory: false
    description: the purpose of float2
    single_value: false
    default_values:
    - 3.14159265359
             